### ISSUE TITLE
Restart crond after change timezone

### ISSUE THREAD

**Issue by laszlolaszlo** [galexrt/ansible-timezone#2]
Hello,

It is recommended to restart crond service after timezone change.

```
---
- name: Set timezone
  ansible.builtin.shell: "timedatectl set-timezone {{ timezone }}; timedatectl"
  register: timedatectl_utc
  notify:
    - Restart crond
  changed_when: "timedatectl_utc.stdout is defined"
  when: "timedatectl.stdout is defined"

```
handlers/main.yaml
```
---
- name: Restart crond
  ansible.builtin.systemd:
    state: restarted
    name: crond


```
